In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore") 
import sys
sys.path.append('../heuristic')
from methods.common import fitness,parse_env

In [2]:
def order_encodere(order):
    A=[[int(x.split('_')[0]),0,int(x.split('_')[1])] for x in order['order'][0]]
    B=[[int(x.split('_')[0]),1,int(x.split('_')[1])] for x in order['order'][1]]
    interval = 1  # 间隔
    # 将列表 B 间隔地插入到列表 A 中
    for i in range(len(B)):
        A.insert((i + 1) * interval + i, B[i])
    return A

def get_fitness(x):
    J, M, A, D, N, pt, p, W = parse_env(x['path'].replace('./','../env/'))
    return -fitness(x['bob'], J, M, A, D, N, pt, p, W)


data_path = pd.read_csv('../env/env_info.csv')
data_path['bob'] = data_path.apply(lambda x : order_encodere(np.load(f'./result/{x["class"]}_{x["excel_num"]}.npz',allow_pickle=True)),axis=1)
data_path['fitness'] = data_path.apply(lambda x: get_fitness(x),axis=1)
data_path.to_csv('../env/bob_info.csv',index=False)

In [ ]:
data_path

,path,class,excel_num,bob,fitness
0,./case1/0.xlsx,1,0,"[[20, 0, 0], [65, 1, 0], [20, 0, 1], [65, 1, 1...",37004.844
1,./case1/1.xlsx,1,1,"[[22, 0, 0], [36, 1, 0], [22, 0, 1], [36, 1, 1...",28876.053
2,./case1/2.xlsx,1,2,"[[53, 0, 0], [2, 1, 0], [53, 0, 1], [2, 1, 1],...",32052.762
3,./case1/3.xlsx,1,3,"[[19, 0, 0], [24, 1, 0], [19, 0, 1], [24, 1, 1...",33055.677
4,./case1/4.xlsx,1,4,"[[41, 0, 0], [47, 1, 0], [41, 0, 1], [47, 1, 1...",30786.165
...,...,...,...,...,...
395,./case4/95.xlsx,4,95,"[[72, 0, 0], [43, 1, 0], [72, 0, 1], [43, 1, 1...",62087.640
396,./case4/96.xlsx,4,96,"[[45, 0, 0], [30, 1, 0], [45, 0, 1], [30, 1, 1...",60011.139
397,./case4/97.xlsx,4,97,"[[45, 0, 0], [33, 1, 0], [45, 0, 1], [33, 1, 1...",66093.708
398,./case4/98.xlsx,4,98,"[[52, 0, 0], [64, 1, 0], [52, 0, 1], [64, 1, 1...",59546.985
399,./case4/99.xlsx,4,99,"[[63, 0, 0], [27, 1, 0], [63, 0, 1], [27, 1, 1...",59072.517